title: Animaquina 
description: A robot IDE for Blender
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Site Repository: https://github.com/luigipacheco/animaquinaweb
  
plugins:
  - jekyll-default-layout
